### ISSUE TITLE
Any Updates to this sections ?

### ISSUE THREAD

**Issue by ShadowDrifterII** [rmusser01/Infosec_Reference#51]
Reverse Engineering
Exploit Development
Fuzzing
Malware
Darknets

Especially the first 3 :D

**Comment by rmusser01** [comment]
Yes, I plan to update all the noted sections. This is a one-person project that I maintain as a free-time thing. I'm not paid and don't receive any compensation for the work I do on this project. Further, I host it on github so that others may be able to provide pull requests with content they would like to see, or feel would help others.
As such, it is a 'when I get around to it'. I do have backlog content for all sections currently, and am planning on making the future backlog public once I get through the current one. 

That being said, feel free to make a pull request for any content in any section you might like, always happy to see pull requests.

**Comment by ShadowDrifterII** [comment]
Keep going bro; you are doing great work

**Comment by rmusser01** [comment]
Thank you!
